apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-ingress
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /flower
        pathType: Prefix
        backend:
          service:
            name: celery-flower
            port:
              number: 5555
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: django-rest
            port:
              number: 8000
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: django-rest
            port:
              number: 8000